### ISSUE TITLE
JS is not working inside encrypted zip file

### ISSUE THREAD

**Issue by tuliomenezes** [CommandFusion/iViewer-For-Android#128]
JS is not working inside encrypted zip file
If you activate debug, you will see that JS is still encrypted

Tested with:
CF 4.0.157
Android MID TM7009, V2.3.4
Rikomagic (clone) , V4.0.4
https://dl.dropboxusercontent.com/u/23807396/teste_enc.zip
https://dl.dropboxusercontent.com/u/23807396/teste_not_enc.zip

**Comment by fpillet** [comment]
Is JS working when NOT using remote debugging?

**Comment by tuliomenezes** [comment]
no, 
you can see the test gui file. There are serial joins controlled by JS. If you download the enc version, JS doesn't work. If you download not enc version, JS works.

**Comment by fpillet** [comment]
Fixed for next build (pushing today to the store), thanks!

**Comment by tuliomenezes** [comment]
still not working with version 4.0.167 (installed via direct link, cause Play Store says my devices are not compatible)

Tested with:
Android MID TM7009, V2.3.4
Rikomagic (clone) , V4.0.4
https://dl.dropboxusercontent.com/u/23807396/teste_enc.zip
https://dl.dropboxusercontent.com/u/23807396/teste_not_enc.zip

**Comment by fpillet** [comment]
Just updated to build 4.0.168 which fixes a couple more issues with debugging and JS, would you mind giving it a go?

Thanks!

**Comment by tuliomenezes** [comment]
almost there; Now I am confusing. 
The encoded test project still doesn't work with .168, but I have another project that JS (a more complex one) is working with .168
with this, JS doesn't work: https://dl.dropboxusercontent.com/u/23807396/teste_enc.zip
with this, JS works: http://www.iluflex.com.br/gui/interface_pro_v2.zip
I will do more tests and let you know.

**Comment by fpillet** [comment]
Ok so there is definite progress! Going to retest teste_enc.zip and check out what's going wrong with this one. I may push another update today. Thanks, as always!

**Comment by fpillet** [comment]
I found the cause of the issue. Pushing out a new build shortly. Thanks!
