### ISSUE TITLE
list, listIndex not being passed from list button javascript

### ISSUE THREAD

**Issue by curtdwar** [CommandFusion/iViewer-For-Android#81]
Pretty sure this is an issue and not a coding error.

My system. Nexus 7, android 4.2.

I was playing about with the XBMC sample GUI and found that none of the actions triggered by selecting items in lists would work. The original untouched code in the javascript field of the button properties is

> XBMCMacMini.playRecentMovie(list, listIndex, join);

join is being sent to the javascript procedure playRecentMovie(), but list and listIndex are not. This is the same for all the lists in the XBMC GUI not just the recentmovies list i used as an example.

So I loaded up my GUI I am putting together and tried something similar, this time i put the code directly in the javascript field for the button properties, hoping to isolate the scope. I used 

> CF.setJoin("s10",list+":"+listIndex+":"+join);

When I press the button, s10 displays "null: -1:d100". I'm a JS novice, so would have suspected it was an error on my part, however it happens with code from the XBMC GUI that I didn't touch, so hopefully this post is in the correct location.

**Comment by fpillet** [comment]
I think this issue is resolved in the next build, due today. Please try it when we announce it on the group and update this issue accordingly. Thanks!

**Comment by curtdwar** [comment]
Still not working. Debugger throws the following error when using the XBMC sample GUI.

> 12:49:59> l9101:2:d1 = 1
> 12:49:59> SCRIPT: Exception running code received from iViewer: ReferenceError: l9101 is not defined
> 12:49:59> SCRIPT: Code that caused the exception: var join="d1",tokens={"[item_index]":"2","[join]":"l9101:2:d1","[id]":"5349","[list_join]":"l9101","[file]":"...."},list=l9101,listIndex=2;XBMCMacMini.playRecentEpisode(list, listIndex, join)
> 12:49:59> l9101:2:d1 = 0

Maybe list=l9101 should be list="l9101".

**Comment by fpillet** [comment]
Yikes! My bad. Thanks for nailing this, will push another build shortly.

**Comment by fpillet** [comment]
Fixed for next build.
