### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by n2hifi** [CommandFusion/iViewer-For-Android#92]
With 113 all of the fonts in the GUI are suddenly much larger than they were before and than they appear in guiDesigner. Same behavior in Nexus 7 and Galaxy S2.

**Comment by fpillet** [comment]
That is correct - fonts appear at their "correct" size. Which font are you using? I think the problem lies in the guiDesigner preview. There was some font size computation on android that was not correct and we fixed it. This changed your font sizes

**Comment by n2hifi** [comment]
I'm using Arial since it is on both the computer and the tablet.  So GUI designer is not showing them the correct size?  Is there a font that will show correctly in GUI designer as well as the tablet?

**Comment by fpillet** [comment]
We'll run some additional tests to ensure font size coherency between GUI Designer and Android iViewer. I think there is some scaling involved that may not be the same on all devices, and this makes things a bit tricky. Better leave this with us than try handling it yourself!

**Comment by fpillet** [comment]
Fixed for next build.

**Comment by n2hifi** [comment]
So I have build 121 and have changed all of my fonts in GUI designer to Driod Sans that I got from the Android SDK.  They still show up quite a bit bigger on the tablet than they do in GUI designer.  I have font size set to normal in Android 4.2.2.

**Comment by fpillet** [comment]
Do you have Droid Sans installed on Windows, or is guiDesigner using a substitution font?

**Comment by n2hifi** [comment]
I have Droid Sans installed on Windows from the Android SDK so there is no substitution on either side.

**Comment by fpillet** [comment]
Next build will have this tweaked. This is mostly an issue related to the density of the display your device has.
