### ISSUE TITLE
IP Address / Host Name same as #95 (sorry)

### ISSUE THREAD

**Issue by MichaelHartmann** [CommandFusion/iViewer-For-Android#99]
When I use the guide designers in the System Properties in the IP Address / Host Name "name.dyndns.org" enter, then the iPad is the IP telegram "standard query a name.dyndns.org" sent. And there is an appropriate response. With Android is not the case.

   <system name="KNXnetIP" ip="wischenhofen.mine.nu" origin="54321" port="3671" protocol="udp" alwayson="1" offlinequeue="1" accept="0" acceptBroadcasts="0" ssl="0" maxconnections="0" heartbeatRx="" heartbeatTx="" heartbeatMode="0" eom="" connectionStatus="0" disconnectionStatus="0">

**Comment by fpillet** [comment]
Fixed for next build. Thanks for reporting!

**Comment by MichaelHartmann** [comment]
Unfortunately, it still does not work with me. Same application works well on i-Pad. Do you have any idea what it is?

**Comment by fpillet** [comment]
An issue was fixed that was failing to trigger hostname resolution, so it should be OK now. Can you email me your GUI so we can investigate the issue? thanks

**Comment by MichaelHartmann** [comment]
Of course ( fpillet@gmail.com).

**Comment by fpillet** [comment]
Michael, please give a go to the just-released build 122 and let me know if it made things better for you.

**Comment by MichaelHartmann** [comment]
Hi Florent, great now is all OK thangs.
Regards MichaelFlorent Pillet notifications@github.com hat geschrieben:
Michael, please give a go to the just-released build 122 and let me know if it made things better for you.

---

**Comment by fpillet** [comment]
Fantastic! Thanks for the feedback and examples!
